env:
  id: "FlappyBird-v0"
  params:
    render_mode: human
    use_lidar : False

model:
  hidden_sizes: [128, 64, 32]
  hidden_activations: [ReLU, ReLU, ReLU]
  output_activation: null

train:
  num_episodes: 10000
  batch_size: 64
  buffer_size: 10000
  gamma: 0.99
  epsilon_start: 0.9
  epsilon_end: 0
  epsilon_decay: 0.001
  warmup_episodes : 500
  learning_rate: 0.0001
